import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docSidebar: [
    'intro',
    {
      type: 'doc',
      label: "Download and Install",
      id: 'download',
    },
    'cabbage3',
    {
      type: 'category',
      label: 'Using Cabbage 3',
      items: [
        'using_cabbage/overview',
        'using_cabbage/running_cabbage',
        'using_cabbage/working_with_instruments',
        'using_cabbage/exporting_instruments',
        'using_cabbage/reserved_channels',
        'using_cabbage/media_files',
        'using_cabbage/multichannel',
        'using_cabbage/commands',
        'using_cabbage/ara_support',

      ],
    },
    {
      type: 'category',
      label: 'UI Layout & Configuration',
      items: [
        'cabbage_widgets/intro',
        {
          type: 'category',
          label: 'Widgets',
          items: [
            'cabbage_widgets/form',
            'cabbage_widgets/button',
            'cabbage_widgets/checkbox',
            'cabbage_widgets/combobox',
            'cabbage_widgets/filebutton',
            'cabbage_widgets/gentable',
            'cabbage_widgets/groupbox',
            'cabbage_widgets/image',
            'cabbage_widgets/keyboard',
            'cabbage_widgets/label',
            'cabbage_widgets/optionButton',
            'cabbage_widgets/horizontalSlider',
            'cabbage_widgets/verticalSlider',
            'cabbage_widgets/rotarySlider',
            'cabbage_widgets/xyPad'
          ],
        }
      ],
    },
    {
      type: 'category',
      label: 'Custom Interfaces',
      items: [
        'custom_interfaces/customWidgets',
        'custom_interfaces/customInterfaces',
        'custom_interfaces/CabbageJS_API',
      ],
    },
    {
      type: 'category',
      label: 'Opcodes',
      items: ['cabbage_opcodes/intro',
        'cabbage_opcodes/cabbageCreate',
        'cabbage_opcodes/cabbageCreateFileName',
        'cabbage_opcodes/cabbageDump',
        'cabbage_opcodes/cabbageGet',
        'cabbage_opcodes/cabbageGetFiles',
        'cabbage_opcodes/cabbageGetValue',
        'cabbage_opcodes/cabbageLoadState',
        'cabbage_opcodes/cabbageSaveState',
        'cabbage_opcodes/cabbageSendMessage',
        'cabbage_opcodes/cabbageSet',
        'cabbage_opcodes/cabbageSetValue'],
    },
    {
      type: 'html',
      value: '<hr style="border: 0; border-top: 1px solid #CCC; margin: 0.5rem 0;" />',
      defaultStyle: true,
    }
  ],

};

export default sidebars;
