name: Deploy Docusaurus Site

permissions:
  contents: write  # This is essential for pushing changes to the repository.
  pages: write     # Required for deploying to GitHub Pages.
on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus site
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Checkout to gh-pages branch
          git checkout -B gh-pages  # This ensures we're on the gh-pages branch, even if it was created remotely

          # Add the build output to git and commit
          git add -f build/
          # rm -rf *  # Be careful with this command; make sure you're in the correct branch!
          # cp -R build/* .
          git commit -m "Deploy website"

          # Push changes to gh-pages branch
          git push --force origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
